name: Full DevOps Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve

    - name: Get Master IP
      run: |
        echo "MASTER_IP=$(terraform -chdir=terraform output -raw master_public_ip)" >> $GITHUB_ENV

    # 🔥 SSH KEY SETUP
    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | sed 's/\\n/\n/g' > key.pem
        chmod 400 key.pem

    - name: Debug Key
      run: |
        head -n 5 key.pem
        wc -l key.pem

    # 🔥 WAIT FOR EC2
    - name: Wait for SSH
      run: |
        until ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$MASTER_IP "echo ready"; do
          echo "Waiting for EC2..."
          sleep 10
        done

    # 🔥 WAIT EXTRA (VERY IMPORTANT)
    - name: Wait for Instance Stabilization
      run: sleep 120

    # 🔥 RUN BOOTSTRAP
    - name: Run Bootstrap
      run: |
        ssh -i key.pem ubuntu@$MASTER_IP "bash -s" < scripts/bootstrap.sh

    # 🔥 APPLY ARGOCD APP
    - name: Apply ArgoCD App
      run: |
        ssh -i key.pem ubuntu@$MASTER_IP "kubectl apply -f devops-ecommerce-kubeadm/argocd/app.yaml"
